var Notifications = Notifications || {};

Notifications.data = {
    APPLICATION_DATA_CHANGE: "data.APPLICATION_DATA_CHANGE"
};

Notifications.ui = {
    INSTANCE_CLICKED: "ui.INSTANCE_CLICKED",
    APPLICATION_CLICKED: "ui.APPLICATION_CLICKED",
    APPLICATION_EXPANDED: "ui.APPLICATION_EXPANDED",
    APPLICATION_EXPANSION_FINISHED: "ui.APPLICATION_EXPANSION_FINISHED",
    APPLICATION_REDUCED: "ui.APPLICATION_REDUCED"
};